# KSP Sentinel Constants

# Crime Statuses
STATUS_REGISTERED = "REGISTERED"
STATUS_INVESTIGATING = "INVESTIGATING"
STATUS_CHARGESHEETED = "CHARGE_SHEETED"
STATUS_CLOSED = "CLOSED"

ALL_STATUSES = [STATUS_REGISTERED, STATUS_INVESTIGATING, STATUS_CHARGESHEETED, STATUS_CLOSED]

# Demographic Categories
VIC_SENIOR_CITIZEN = "SENIOR_CITIZEN"
VIC_WOMAN = "WOMAN"
VIC_CHILD = "CHILD"
VIC_GENERAL = "GENERAL"

# Default Map Center (Karnataka Centroid)
KARNATAKA_CENTER_LAT = 15.3173
KARNATAKA_CENTER_LNG = 75.7139
MAP_DEFAULT_ZOOM = 7
